build_source        = "docker.ubuntu"
image_home_dir      = "/"
dist_path           = "./dist"
ssl_cert_key_source = "../../../tests/privkey.pem.test"
ssl_cert_source     = "../../../tests/fullchain.pem.test"
react_domain        = "app.paion-data.com"
