# Copyright 2024 Paion Data. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Immutable Infrastructure as a Service CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  cancel-previous:
    name: Cancel Previous Runs In Order to Allocate Action Resources Immediately for Current Run
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.10.1
        if: ${{github.ref != 'refs/head/master'}}
        with:
          access_token: ${{ github.token }}

  yml-md-style-and-link-checks:
    uses: paion-data/github-actions-core/.github/workflows/yml-md-style-and-link-checks.yml@master

  packer-file-linting:
    name: Packer Files Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-packer@v3
      - run: packer fmt -check -recursive .

  terraform-file-linting:
    name: Terraform Files Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive

  docker-base-images:
    name: Publish docker images for "Packer Image Build Test"
    needs: [yml-md-style-and-link-checks, packer-file-linting, terraform-file-linting]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        docker: [
          # {dockerfile-path: tests/machine-learning, image-name: iiaas-machine-learning-test-base},
          # {dockerfile-path: tests/react, image-name: iiaas-react-test-base},
          {dockerfile-path: tests/kong-api-gateway, image-name: iiaas-kong-api-gateway-test-base},
          # {dockerfile-path: tests/webservice, image-name: iiaas-webservice-test-base},
          # {dockerfile-path: tests/elk, image-name: iiaas-elk-test-base}
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: paiondata
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Base image to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker.dockerfile-path }}
          push: true
          tags: paiondata/${{ matrix.docker.image-name }}:latest

  packer-tests:
    name: Image Build Test
    needs: docker-base-images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests: [
          {test-directory: tests/kong-api-gateway/images, image-name: iiaas-kong-api-gateway-test},
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker for Images Tests
        uses: docker-practice/actions-setup-docker@master
      - name: Test Packer Build
        run: |
          cd ${{ matrix.tests.test-directory }}
          ./run-tests.sh
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: paiondata
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Test image to DockerHub
        run: docker push paiondata/${{ matrix.tests.image-name }}:latest

  terraform-it-tests:
    name: Terraform Integration Tests
    needs: packer-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        it-tests: [
          {test-directory: tests/kong-api-gateway/instances},
        ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ${{ matrix.it-tests.test-directory }}
          terraform init
          terraform test

  documentation-ci-cd:
    name: Test Documentation Build & Deploy Documentation to GitHub Pages
    needs: [terraform-it-tests]
    outputs:
      outcome: ${{ job.status }}
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
        working-directory: docs
      - name: Build website
        run: yarn build
        working-directory: docs
      - name: Load CNAME file
        if: github.ref == 'refs/heads/master'
        run: cp docs/CNAME docs/build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: qing-wq
          user_email: 2702461713@qq.com
